services:
  backend:
    build:
      context: ./tokenizacao-app/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - RPC_URL=http://anvil:8545
      - CHAIN_ID=1337
      - DATABASE_URL=sqlite:./tokenizacao.db
    volumes:
      - ./tokenizacao-app/backend/.env:/app/.env:ro
    depends_on:
      - anvil
    networks:
      - tokeniza-network

  frontend:
    build:
      context: ./tokenizacao-app/app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
      - NEXT_PUBLIC_ANVIL_RPC_URL=http://localhost:8545
    depends_on:
      - backend
    networks:
      - tokeniza-network

  anvil:
    build:
      context: ./tokenizacao-app/onchain
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    command: ["anvil", "--host", "0.0.0.0", "--port", "8545"]
    networks:
      - tokeniza-network

networks:
  tokeniza-network:
    driver: bridge

volumes:
  blockchain_data: