services:
  - type: web
    name: tokenizacao-backend
    runtime: rust
    buildCommand: cargo build --release
    startCommand: ./target/release/tokenizacao-backend
    plan: free
    region: ohio
    envVars:
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "10000"
      - key: RPC_URL
        value: "https://sepolia.era.zksync.dev"
      - key: CHAIN_ID
        value: "300"
      - key: PRIVATE_KEY
        value: "0x5b161397b1a9d087665e3dde45bec7b382fc7cca66542ad587abc83848ff021c"
      - key: ASSETTOKEN_ADDRESS
        value: "0xC2B8d5aefD7d490314D4f9c7ff6dFa129670CE64"
      - key: MARKETPLACE_ADDRESS
        value: "0x61b2bC16fc652418FB15D4a319b31E1853f38B84"
      - key: WAITLIST_ADDRESS
        value: "0x019ab49cE22877EA615b5c544cAA178525266b51"
      - key: RUST_LOG
        value: "info"
      - key: DATABASE_URL
        value: "sqlite:./tokenizacao.db"
